# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Rain Drop
subtitle:
description: Write for Life
author: Azuki
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://jie211.github.io/blog
url: https://Jie211.github.io/
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: apollo

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Jie211/jie211.github.io.git
  branch: master
  message: "^_^ Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

  # type: git
  # repo: git@github.com:Jie211/blog.git
  # branch: gh-pages
  # message: "^_^ Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

# archive_dir
archive_generator:
  per_page: 20
  yearly: true
  monthly: false
  daily: false

# generator-tag
tag_generator:
  per_page: 10

# hexo-hey
admin:
  name: chen
  password: azuki
  secret: who let the dog out
  expire: 60*1

# hexo-prosm
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'default'

# robotstxt
robotstxt:
  useragent: "*"
  sitemap: 
    - /sitemap.xml
    - /baidusitemap.xml

# sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# uglify - javscript minify
uglify:
  mangle: true
  output:
  compress:
  exclude: 
    - "*.min.js"

# clean-css - css minify
clean_css:
  exclude:
   - "*.min.css"
# html minify
html_minifier:
  exclude:
  removeComments: true
  removeCommentsFromCDATA: false 
  removeCDATASectionsFromCDATA: false 
  collapseWhitespace: true 
  conservativeCollapse: true 
  preserveLineBreaks: true
  collapseBooleanAttributes: false 
  removeAttributeQuotes: false
  removeRedundantAttributes: false 
  preventAttributesEscaping: false
  useShortDoctype: false
  removeEmptyAttributes: false 
  removeScriptTypeAttributes: false
  removeStyleLinkTypeAttributes: false
  removeOptionalTags: false
  removeIgnored: false
  removeEmptyElements: false
  lint: false
  keepClosingSlash: false
  caseSensitive: false
  minifyJS: true
  minifyCSS: true
  minifyURLs: false
